n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
n3 = int(input('Digite o terceiro número: '))
n4 = int(input('Digite o quarto número: '))
soma = (n1 + n2 + n3 + n4) 
print (f'A soma dos números é:{soma}')
produto = (n1 * n2 * n3 * n4) 
print (f'O produto dos números é: {produto}')